baseURL = "https://foixgrass.fr/"
languageCode = 'fr'
title = 'FoixGrass Festival'
theme = "paper"

[params]
  description = "Festival de Bluegrass en Ariège — 20 au 23 Août 2026 — Ganac (09)"
  images = ["img/logo-foixgrass.jpeg"]
  favicon = "favicon.ico"
  appleTouchIcon = "apple-touch-icon.png"
